---
slug: padrino_book
filename: padrino_book
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 6c8510be-6356-439b-ae6f-8629021a0418
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
